### ISSUE TITLE
Major Bug - Bot counts self invites

### ISSUE THREAD

**Issue by JustaRandomGuy02** [FrancisLaTruelle/InviteManagerMongoDB#5]
If you make a invite of your own, and join the server with the invite and leave repeatedly, it just counts it on and on.
![image](https://user-images.githubusercontent.com/86528735/132043734-e988dfb1-9fb6-4d8c-87f5-447af4fe991d.png)

**Comment by FrancisLaTruelle** [comment]
The trick is smarter than me, I forgot that during development. I correct it as quickly as possible because I understand that it is very problematic for its operation.

**Comment by FrancisLaTruelle** [comment]
Normally this should fix your bug. Do not hesitate to open other issues if you have any problems.

**Comment by noob-coder69** [comment]
it not removing invites now if a person leaves the server
